### ISSUE TITLE
Enchancment: Update to add new Dasduino Core, Connect, ConnectPlus... boards

### ISSUE THREAD

**Issue by NotHavocc** [e-radionicacom/e-radionica.com-Fritzing-Library-parts-#4]
Hello, i use a Dasduino Core board as the board for every project i make, even the ones i upload on github. To make digital connection schematics, please add the new Dasduino boards. Thanks.

**Comment by rsoric** [comment]
Hi @NotHavocc 

We're working on it, recently we did some research into how to do this in the best possible way and we think we found a good method. They will be added to Fritzing sometime soon, I can't give you an exact date, but it's in the backlog.

I'll make sure to write to you here when they're added.

-Rob
